/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dao;

import java.util.Date;
import com.monedafrontera.dto.*;
import com.monedafrontera.exceptions.*;

public interface TasadebolivaroficinaDao
{
	/** 
	 * Inserts a new row in the tasadebolivaroficina table.
	 */
	public TasadebolivaroficinaPk insert(Tasadebolivaroficina dto) throws TasadebolivaroficinaDaoException;

	/** 
	 * Updates a single row in the tasadebolivaroficina table.
	 */
	public void update(TasadebolivaroficinaPk pk, Tasadebolivaroficina dto) throws TasadebolivaroficinaDaoException;

	/** 
	 * Deletes a single row in the tasadebolivaroficina table.
	 */
	public void delete(TasadebolivaroficinaPk pk) throws TasadebolivaroficinaDaoException;

	/** 
	 * Returns the rows from the tasadebolivaroficina table that matches the specified primary-key value.
	 */
	public Tasadebolivaroficina findByPrimaryKey(TasadebolivaroficinaPk pk) throws TasadebolivaroficinaDaoException;

	/** 
	 * Returns all rows from the tasadebolivaroficina table that match the criteria 'fecha = :fecha AND tipo = :tipo'.
	 */
	public Tasadebolivaroficina findByPrimaryKey(Date fecha, String tipo) throws TasadebolivaroficinaDaoException;

	/** 
	 * Returns all rows from the tasadebolivaroficina table that match the criteria ''.
	 */
	public Tasadebolivaroficina[] findAll() throws TasadebolivaroficinaDaoException;

	/** 
	 * Returns all rows from the tasadebolivaroficina table that match the criteria 'tipo = :tipo'.
	 */
	public Tasadebolivaroficina[] findWhereTipoEquals(String tipo) throws TasadebolivaroficinaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tasadebolivaroficina table that match the specified arbitrary SQL statement
	 */
	public Tasadebolivaroficina[] findByDynamicSelect(String sql, Object[] sqlParams) throws TasadebolivaroficinaDaoException;

	/** 
	 * Returns all rows from the tasadebolivaroficina table that match the specified arbitrary SQL statement
	 */
	public Tasadebolivaroficina[] findByDynamicWhere(String sql, Object[] sqlParams) throws TasadebolivaroficinaDaoException;

}
