/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.factory;

import java.sql.Connection;
import com.monedafrontera.dao.*;
import com.monedafrontera.jdbc.*;

public class DolartodayDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return DolartodayDao
	 */
	public static DolartodayDao create()
	{
		return new DolartodayDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return DolartodayDao
	 */
	public static DolartodayDao create(Connection conn)
	{
		return new DolartodayDaoImpl( conn );
	}

}
