/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the dolartoday table.
 */
public class DolartodayPk implements Serializable
{
	protected long epoch;

	/** 
	 * This attribute represents whether the primitive attribute epoch is null.
	 */
	protected boolean epochNull;

	/** 
	 * Sets the value of epoch
	 */
	public void setEpoch(long epoch)
	{
		this.epoch = epoch;
	}

	/** 
	 * Gets the value of epoch
	 */
	public long getEpoch()
	{
		return epoch;
	}

	/**
	 * Method 'DolartodayPk'
	 * 
	 */
	public DolartodayPk()
	{
	}

	/**
	 * Method 'DolartodayPk'
	 * 
	 * @param epoch
	 */
	public DolartodayPk(final long epoch)
	{
		this.epoch = epoch;
	}

	/** 
	 * Sets the value of epochNull
	 */
	public void setEpochNull(boolean epochNull)
	{
		this.epochNull = epochNull;
	}

	/** 
	 * Gets the value of epochNull
	 */
	public boolean isEpochNull()
	{
		return epochNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DolartodayPk)) {
			return false;
		}
		
		final DolartodayPk _cast = (DolartodayPk) _other;
		if (epoch != _cast.epoch) {
			return false;
		}
		
		if (epochNull != _cast.epochNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (epoch ^ (epoch >>> 32));
		_hashCode = 29 * _hashCode + (epochNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.DolartodayPk: " );
		ret.append( "epoch=" + epoch );
		return ret.toString();
	}

}
