/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the pais table.
 */
public class PaisPk implements Serializable
{
	protected String codigopais;

	/** 
	 * Sets the value of codigopais
	 */
	public void setCodigopais(String codigopais)
	{
		this.codigopais = codigopais;
	}

	/** 
	 * Gets the value of codigopais
	 */
	public String getCodigopais()
	{
		return codigopais;
	}

	/**
	 * Method 'PaisPk'
	 * 
	 */
	public PaisPk()
	{
	}

	/**
	 * Method 'PaisPk'
	 * 
	 * @param codigopais
	 */
	public PaisPk(final String codigopais)
	{
		this.codigopais = codigopais;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PaisPk)) {
			return false;
		}
		
		final PaisPk _cast = (PaisPk) _other;
		if (codigopais == null ? _cast.codigopais != codigopais : !codigopais.equals( _cast.codigopais )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigopais != null) {
			_hashCode = 29 * _hashCode + codigopais.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.PaisPk: " );
		ret.append( "codigopais=" + codigopais );
		return ret.toString();
	}

}
