/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import com.monedafrontera.dao.*;
import com.monedafrontera.factory.*;
import com.monedafrontera.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Pais implements Serializable
{
	/** 
	 * This attribute maps to the column codigopais in the pais table.
	 */
	protected String codigopais;

	/** 
	 * This attribute maps to the column nombre in the pais table.
	 */
	protected String nombre;

	/** 
	 * This attribute maps to the column estado in the pais table.
	 */
	protected int estado;

	/** 
	 * This attribute represents whether the primitive attribute estado is null.
	 */
	protected boolean estadoNull = true;

	/**
	 * Method 'Pais'
	 * 
	 */
	public Pais()
	{
	}

	/**
	 * Method 'getCodigopais'
	 * 
	 * @return String
	 */
	public String getCodigopais()
	{
		return codigopais;
	}

	/**
	 * Method 'setCodigopais'
	 * 
	 * @param codigopais
	 */
	public void setCodigopais(String codigopais)
	{
		this.codigopais = codigopais;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return int
	 */
	public int getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(int estado)
	{
		this.estado = estado;
		this.estadoNull = false;
	}

	/**
	 * Method 'setEstadoNull'
	 * 
	 * @param value
	 */
	public void setEstadoNull(boolean value)
	{
		this.estadoNull = value;
	}

	/**
	 * Method 'isEstadoNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstadoNull()
	{
		return estadoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Pais)) {
			return false;
		}
		
		final Pais _cast = (Pais) _other;
		if (codigopais == null ? _cast.codigopais != codigopais : !codigopais.equals( _cast.codigopais )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		if (estadoNull != _cast.estadoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigopais != null) {
			_hashCode = 29 * _hashCode + codigopais.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		_hashCode = 29 * _hashCode + estado;
		_hashCode = 29 * _hashCode + (estadoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PaisPk
	 */
	public PaisPk createPk()
	{
		return new PaisPk(codigopais);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.Pais: " );
		ret.append( "codigopais=" + codigopais );
		ret.append( ", nombre=" + nombre );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
