/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tasadebolivaroficina table.
 */
public class TasadebolivaroficinaPk implements Serializable
{
	protected Date fecha;

	protected String tipo;

	/** 
	 * Sets the value of fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/** 
	 * Gets the value of fecha
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/** 
	 * Sets the value of tipo
	 */
	public void setTipo(String tipo)
	{
		this.tipo = tipo;
	}

	/** 
	 * Gets the value of tipo
	 */
	public String getTipo()
	{
		return tipo;
	}

	/**
	 * Method 'TasadebolivaroficinaPk'
	 * 
	 */
	public TasadebolivaroficinaPk()
	{
	}

	/**
	 * Method 'TasadebolivaroficinaPk'
	 * 
	 * @param fecha
	 * @param tipo
	 */
	public TasadebolivaroficinaPk(final Date fecha, final String tipo)
	{
		this.fecha = fecha;
		this.tipo = tipo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TasadebolivaroficinaPk)) {
			return false;
		}
		
		final TasadebolivaroficinaPk _cast = (TasadebolivaroficinaPk) _other;
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (tipo == null ? _cast.tipo != tipo : !tipo.equals( _cast.tipo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		if (tipo != null) {
			_hashCode = 29 * _hashCode + tipo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.TasadebolivaroficinaPk: " );
		ret.append( "fecha=" + fecha );
		ret.append( ", tipo=" + tipo );
		return ret.toString();
	}

}
