/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tasadolar table.
 */
public class TasadolarPk implements Serializable
{
	protected String codigopais;

	protected Date fecha;

	/** 
	 * Sets the value of codigopais
	 */
	public void setCodigopais(String codigopais)
	{
		this.codigopais = codigopais;
	}

	/** 
	 * Gets the value of codigopais
	 */
	public String getCodigopais()
	{
		return codigopais;
	}

	/** 
	 * Sets the value of fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/** 
	 * Gets the value of fecha
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'TasadolarPk'
	 * 
	 */
	public TasadolarPk()
	{
	}

	/**
	 * Method 'TasadolarPk'
	 * 
	 * @param codigopais
	 * @param fecha
	 */
	public TasadolarPk(final String codigopais, final Date fecha)
	{
		this.codigopais = codigopais;
		this.fecha = fecha;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TasadolarPk)) {
			return false;
		}
		
		final TasadolarPk _cast = (TasadolarPk) _other;
		if (codigopais == null ? _cast.codigopais != codigopais : !codigopais.equals( _cast.codigopais )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigopais != null) {
			_hashCode = 29 * _hashCode + codigopais.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.TasadolarPk: " );
		ret.append( "codigopais=" + codigopais );
		ret.append( ", fecha=" + fecha );
		return ret.toString();
	}

}
