/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import com.monedafrontera.dao.*;
import com.monedafrontera.factory.*;
import com.monedafrontera.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tasadolar implements Serializable
{
	/** 
	 * This attribute maps to the column codigopais in the tasadolar table.
	 */
	protected String codigopais;

	/** 
	 * This attribute maps to the column fecha in the tasadolar table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column tasa in the tasadolar table.
	 */
	protected float tasa;

	/** 
	 * This attribute represents whether the primitive attribute tasa is null.
	 */
	protected boolean tasaNull = true;

	/** 
	 * This attribute maps to the column tasadolar in the tasadolar table.
	 */
	protected float tasadolar;

	/** 
	 * This attribute represents whether the primitive attribute tasadolar is null.
	 */
	protected boolean tasadolarNull = true;

	/** 
	 * This attribute maps to the column trm in the tasadolar table.
	 */
	protected float trm;

	/** 
	 * This attribute represents whether the primitive attribute trm is null.
	 */
	protected boolean trmNull = true;

	/**
	 * Method 'Tasadolar'
	 * 
	 */
	public Tasadolar()
	{
	}

	/**
	 * Method 'getCodigopais'
	 * 
	 * @return String
	 */
	public String getCodigopais()
	{
		return codigopais;
	}

	/**
	 * Method 'setCodigopais'
	 * 
	 * @param codigopais
	 */
	public void setCodigopais(String codigopais)
	{
		this.codigopais = codigopais;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getTasa'
	 * 
	 * @return float
	 */
	public float getTasa()
	{
		return tasa;
	}

	/**
	 * Method 'setTasa'
	 * 
	 * @param tasa
	 */
	public void setTasa(float tasa)
	{
		this.tasa = tasa;
		this.tasaNull = false;
	}

	/**
	 * Method 'setTasaNull'
	 * 
	 * @param value
	 */
	public void setTasaNull(boolean value)
	{
		this.tasaNull = value;
	}

	/**
	 * Method 'isTasaNull'
	 * 
	 * @return boolean
	 */
	public boolean isTasaNull()
	{
		return tasaNull;
	}

	/**
	 * Method 'getTasadolar'
	 * 
	 * @return float
	 */
	public float getTasadolar()
	{
		return tasadolar;
	}

	/**
	 * Method 'setTasadolar'
	 * 
	 * @param tasadolar
	 */
	public void setTasadolar(float tasadolar)
	{
		this.tasadolar = tasadolar;
		this.tasadolarNull = false;
	}

	/**
	 * Method 'setTasadolarNull'
	 * 
	 * @param value
	 */
	public void setTasadolarNull(boolean value)
	{
		this.tasadolarNull = value;
	}

	/**
	 * Method 'isTasadolarNull'
	 * 
	 * @return boolean
	 */
	public boolean isTasadolarNull()
	{
		return tasadolarNull;
	}

	/**
	 * Method 'getTrm'
	 * 
	 * @return float
	 */
	public float getTrm()
	{
		return trm;
	}

	/**
	 * Method 'setTrm'
	 * 
	 * @param trm
	 */
	public void setTrm(float trm)
	{
		this.trm = trm;
		this.trmNull = false;
	}

	/**
	 * Method 'setTrmNull'
	 * 
	 * @param value
	 */
	public void setTrmNull(boolean value)
	{
		this.trmNull = value;
	}

	/**
	 * Method 'isTrmNull'
	 * 
	 * @return boolean
	 */
	public boolean isTrmNull()
	{
		return trmNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tasadolar)) {
			return false;
		}
		
		final Tasadolar _cast = (Tasadolar) _other;
		if (codigopais == null ? _cast.codigopais != codigopais : !codigopais.equals( _cast.codigopais )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (tasa != _cast.tasa) {
			return false;
		}
		
		if (tasaNull != _cast.tasaNull) {
			return false;
		}
		
		if (tasadolar != _cast.tasadolar) {
			return false;
		}
		
		if (tasadolarNull != _cast.tasadolarNull) {
			return false;
		}
		
		if (trm != _cast.trm) {
			return false;
		}
		
		if (trmNull != _cast.trmNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigopais != null) {
			_hashCode = 29 * _hashCode + codigopais.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(tasa);
		_hashCode = 29 * _hashCode + (tasaNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(tasadolar);
		_hashCode = 29 * _hashCode + (tasadolarNull ? 1 : 0);
		_hashCode = 29 * _hashCode + Float.floatToIntBits(trm);
		_hashCode = 29 * _hashCode + (trmNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TasadolarPk
	 */
	public TasadolarPk createPk()
	{
		return new TasadolarPk(codigopais, fecha);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.Tasadolar: " );
		ret.append( "codigopais=" + codigopais );
		ret.append( ", fecha=" + fecha );
		ret.append( ", tasa=" + tasa );
		ret.append( ", tasadolar=" + tasadolar );
		ret.append( ", trm=" + trm );
		return ret.toString();
	}

}
