/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.monedafrontera.dto;

import com.monedafrontera.dao.*;
import com.monedafrontera.factory.*;
import com.monedafrontera.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tasadebolivaroficina implements Serializable
{
	/** 
	 * This attribute maps to the column fecha in the tasadebolivaroficina table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column preciobolivar in the tasadebolivaroficina table.
	 */
	protected float preciobolivar;

	/** 
	 * This attribute represents whether the primitive attribute preciobolivar is null.
	 */
	protected boolean preciobolivarNull = true;

	/** 
	 * This attribute maps to the column tipo in the tasadebolivaroficina table.
	 */
	protected String tipo;

	/**
	 * Method 'Tasadebolivaroficina'
	 * 
	 */
	public Tasadebolivaroficina()
	{
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getPreciobolivar'
	 * 
	 * @return float
	 */
	public float getPreciobolivar()
	{
		return preciobolivar;
	}

	/**
	 * Method 'setPreciobolivar'
	 * 
	 * @param preciobolivar
	 */
	public void setPreciobolivar(float preciobolivar)
	{
		this.preciobolivar = preciobolivar;
		this.preciobolivarNull = false;
	}

	/**
	 * Method 'setPreciobolivarNull'
	 * 
	 * @param value
	 */
	public void setPreciobolivarNull(boolean value)
	{
		this.preciobolivarNull = value;
	}

	/**
	 * Method 'isPreciobolivarNull'
	 * 
	 * @return boolean
	 */
	public boolean isPreciobolivarNull()
	{
		return preciobolivarNull;
	}

	/**
	 * Method 'getTipo'
	 * 
	 * @return String
	 */
	public String getTipo()
	{
		return tipo;
	}

	/**
	 * Method 'setTipo'
	 * 
	 * @param tipo
	 */
	public void setTipo(String tipo)
	{
		this.tipo = tipo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tasadebolivaroficina)) {
			return false;
		}
		
		final Tasadebolivaroficina _cast = (Tasadebolivaroficina) _other;
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (preciobolivar != _cast.preciobolivar) {
			return false;
		}
		
		if (preciobolivarNull != _cast.preciobolivarNull) {
			return false;
		}
		
		if (tipo == null ? _cast.tipo != tipo : !tipo.equals( _cast.tipo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(preciobolivar);
		_hashCode = 29 * _hashCode + (preciobolivarNull ? 1 : 0);
		if (tipo != null) {
			_hashCode = 29 * _hashCode + tipo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TasadebolivaroficinaPk
	 */
	public TasadebolivaroficinaPk createPk()
	{
		return new TasadebolivaroficinaPk(fecha, tipo);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.monedafrontera.dto.Tasadebolivaroficina: " );
		ret.append( "fecha=" + fecha );
		ret.append( ", preciobolivar=" + preciobolivar );
		ret.append( ", tipo=" + tipo );
		return ret.toString();
	}

}
